global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - '192.168.1.107:8080'
          - '192.168.1.100:8080'
          - '192.168.1.104:8080'