# Step 1: Modules caching
FROM golang:1.19.2-alpine3.16 as modules

ENV GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0

COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.19.2-alpine3.16 as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app

ENV GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0

RUN go build -tags migrate -o /bin/app ./cmd/barista

# Step 3: Final
FROM scratch

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/barista/config.yml /
COPY --from=builder /app/db/migrations /db/migrations
COPY --from=builder /bin/app /app
CMD ["/app"]